tagFormat: '${version}'
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - ./test/build.sbt
        - CHANGELOG.md
  - '@semantic-release/github'
  