tagFormat: '${version}'
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@google/semantic-release-replace-plugin'
    - replacements:
        - files:
            - ./test/build.sbt
          from: 'version := .*'
          to: 'version := "${nextRelease.version}",'
          results:
            - file: ./test/build.sbt
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - '@semantic-release/git'
    - assets:
        - ./test/build.sbt
        - CHANGELOG.md
  - '@semantic-release/github'
  